[package]
name = "boardgame-api"
version = "0.1.0"
authors = ["Akio-m <ahigachika@gmail.com>"]
edition = "2018"

[dependencies]
tide = "0.14.0"
async-std = { version = "1.6.0", features = ["attributes"] }
serde = "1.0.117"
serde_json = "1.0"
